#!/bin/bash
PL_PREFIX=$(pwd)/local
PL_CPPFLAGS="$PL_CPPFLAGS -I$PL_PREFIX/include \
  -I$PL_PREFIX/include/cvc3 \
  -I$PL_PREFIX/z3/lib -I$PL_PREFIX/z3/c++"
PL_LDFLAGS="$PL_LDFLAGS -L$PL_PREFIX/lib -L$PL_PREFIX/z3/bin/external"

SIGSEGV_DIR=libsigsegv-2.10
TECLA_DIR=libtecla
BUDDY_DIR=buddy-2.4
GMP_DIR=gmp-5.0.5
CVC3_DIR=cvc3
Z3_DIR=z3
SMTA_DIR=smta-0.1
MAUDE_DIR=Maude-2.6

JOBS="-j 9"


download=false
while :; do
  case "$1" in
    --download) download=true; shift;;
    *) break ;;
  esac
done


# download all sources
if [ $download = true ] ; then

rm -rf $PL_PREFIX
mkdir $PL_PREFIX
cd $PL_PREFIX

WGET=wget
HG="hg clone"
GIT="git clone"
#TAR="tar --recursive-unlink --extract --gunzip --verbose"
TAR="tar xvfz"

SIGSEGV_TAR=$SIGSEGV_DIR.tar.gz
TECLA_TAR=$TECLA_DIR.tar.gz
BUDDY_TAR=$BUDDY_DIR.tar.gz
GMP_TAR=$GMP_DIR.tar.xz
CVC3_TAR=cvc3-latest.tar.gz

BUDDY_MIRROR="http://downloads.sourceforge.net/project/buddy/buddy/BuDDy%202.4/buddy-2.4.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fbuddy%2F&ts=1305827031&use_mirror=voxel"

# libsigsegv
$WGET http://ftp.gnu.org/gnu/libsigsegv/$SIGSEGV_TAR
$TAR $SIGSEGV_TAR
rm $SIGSEGV_TAR

# libtecla
$WGET http://www.astro.caltech.edu/~mcs/tecla/$TECLA_TAR
$TAR $TECLA_TAR
rm $TECLA_TAR

# buddy
$WGET -O $BUDDY_TAR $BUDDY_MIRROR
$TAR $BUDDY_TAR
rm $BUDDY_TAR

# gmp
$WGET ftp://ftp.gnu.org/gnu/gmp/$GMP_TAR
$TAR $GMP_TAR
rm $GMP_TAR


# cvc3
$WGET -O $CVC3_TAR http://goedel.cims.nyu.edu/cvc3-builds/latest.tar.gz
$TAR $CVC3_TAR
mv $(basename cvc3-*) $CVC3_DIR
rm $CVC3_TAR

# z3
$GIT https://git01.codeplex.com/z3 $Z3_DIR

cd -

fi


# libsigsegv
cd $PL_PREFIX/$SIGSEGV_DIR
./configure --prefix=$PL_PREFIX \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS" CXXFLAGS="$PL_CXXFLAGS"
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $PL_PREFIX/$SIGSEGV_DIR $JOBS install
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi

# libtecla
cd $PL_PREFIX/$TECLA_DIR
./configure --prefix=$PL_PREFIX --build=$PL_BUILD \
    --with-man-pages=no \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS -D_POSIX_C_SOURCE=1" CXXFLAGS="$PL_CXXFLAGS"
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $PL_PREFIX/$TECLA_DIR TARGETS=normal TARGET_LIBS=static install
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi

# buddy
cd $PL_PREFIX/$BUDDY_DIR
./configure --prefix=$PL_PREFIX --build=$PL_BUILD \
    --disable-shared \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS" CXXFLAGS="$PL_CXXFLAGS"
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $PL_PREFIX/$BUDDY_DIR $JOBS install
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi


# gmp
cd $PL_PREFIX/$GMP_DIR
#./.bootstrap
./configure --prefix=$PL_PREFIX --build=$PL_BUILD \
    --enable-cxx --disable-shared \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS" CXXFLAGS="$PL_CXXFLAGS"
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $PL_PREFIX/$GMP_DIR $JOBS install
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi


# cvc3
cd $PL_PREFIX/$CVC3_DIR
./configure --prefix=$PL_PREFIX --build=$PL_BUILD \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS" CXXFLAGS="$PL_CXXFLAGS" CPPFLAGS="$PL_CPPFLAGS" \
    LDFLAGS="$PL_LDFLAGS" LIBS="-lgmp"
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $PL_PREFIX/$CVC3_DIR $JOBS install
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi

# z3
cd $PL_PREFIX/$Z3_DIR
autoconf
./configure --prefix=$PL_PREFIX --build=$PL_BUILD \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS" CXXFLAGS="$PL_CXXFLAGS" \
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $PL_PREFIX/$Z3_DIR $JOBS a
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi


# smta
make -C $SMTA_DIR CXXFLAGS="-Wall $PL_CXXFLAGS" install
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi


# maude
cd $MAUDE_DIR
./configure --prefix=$PL_PREFIX --build=$PL_BUILD \
    CC=$PL_CC CXX=$PL_CXX \
    CFLAGS="$PL_CFLAGS" CXXFLAGS="$PL_CXXFLAGS" CPPFLAGS="$PL_CPPFLAGS" \
    LDFLAGS="$PL_LDFLAGS" LIBS="-lsmta -lz3 -lcvc3 -lgmp"
exit_code=$?
cd -
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi
make -C $MAUDE_DIR
exit_code=$?
if [ $exit_code -ne 0 ] ; then
  exit $exit_code
fi

