#!/bin/bash
DOWNLOAD_DIR=.downloads
SIGSEGV_TAR=libsigsegv-2.10.tar.gz
TECLA_TAR=libtecla.tar.gz
BUDDY_TAR=buddy-2.4.tar.gz
GMP_TAR=gmp-5.0.2.tar.gz
CVC3_TAR=cvc3-latest.tar.gz

# fetch the archives
rm -rf ${DOWNLOAD_DIR}
mkdir ${DOWNLOAD_DIR}
cd ${DOWNLOAD_DIR}

BUDDY_MIRROR="http://downloads.sourceforge.net/project/buddy/buddy/BuDDy%202.4/buddy-2.4.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fbuddy%2F&ts=1305827031&use_mirror=voxel"

WGET=wget
HG="hg clone"
GIT="git clone"
#${WGET} http://ftp.gnu.org/gnu/libsigsegv/${SIGSEGV_TAR}
${GIT} git://git.savannah.gnu.org/libsigsegv.git 
${WGET} http://www.astro.caltech.edu/~mcs/tecla/${TECLA_TAR}
${WGET} -O ${BUDDY_TAR} ${BUDDY_MIRROR}
#${WGET} ftp://ftp.gnu.org/gnu/gmp/${GMP_TAR}
${HG} http://gmplib.org:8000/gmp-5.0
${WGET} -O ${CVC3_TAR} http://goedel.cims.nyu.edu/cvc3-builds/latest.tar.gz
${GIT} clone https://git01.codeplex.com/z3

cd -

# unpack the achives
TAR="tar --recursive-unlink --extract --gunzip --verbose"
${TAR} --file=${DOWNLOAD_DIR}/${SIGSEGV_TAR}
${TAR} --file=${DOWNLOAD_DIR}/${TECLA_TAR}
${TAR} --file=${DOWNLOAD_DIR}/${BUDDY_TAR}
${TAR} --file=${DOWNLOAD_DIR}/${GMP_TAR}
${TAR} --file=${DOWNLOAD_DIR}/${CVC3_TAR}

rm -rf ${DOWNLOAD_DIR}

